export const RECEIVE_PHOTOS = 'RECEIVE_PHOTOS'
export const UPDATE_IMAGE_SIZE = 'UPDATE_IMAGE_SIZE'
export const UPDATE_IMAGE_FILTER = 'UPDATE_IMAGE_FILTER'
export const UPDATE_PHOTO = 'UPDATE_PHOTO'
